routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/map', 'MapController@indexJob')->name('map');
Route::get('/map/services', 'MapController@indexService')->name('map.services');
Route::post('/map/search-job', 'MapController@indexJob')->name('map.searchMapJob');
Route::post('/map/search-service', 'MapController@indexService')->name('map.searchMapService');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/my-profile', 'UserController@MyProfile')->name('myProfile');
Route::get('/my-jobs', 'JobController@MyJobs')->name('myJobs');
Route::get('/my-services', 'ServiceController@MyServices')->name('myServices');
Route::get('/profile/{id}', 'UserController@profile')->name('profile');
Route::post('/profile-update/about', 'UserController@UpdateAbout')->name('profile.updateAbout');
Route::post('/profile-update/contact', 'UserController@UpdateContact')->name('profile.updateContact');
Route::post('/profile-update/account', 'UserController@UpdateAccount')->name('profile.updateAccount');
Route::post('/profile-update/socials', 'UserController@UpdateSocials')->name('profile.updateSocials');
Route::post('/profile-update/photo', 'UserController@UpdatePhoto')->name('profile.updatePhoto');
Route::resource('/job', 'JobController');
Route::get('/job-search', 'JobController@search');
Route::resource('/service', 'ServiceController');
Route::post('/service/delete', 'ServiceController@delete');
Route::get('/cancel-services', 'JobController@cancelServices');
Route::get('/pay-services', 'JobController@payServices');
Route::get('/pending-services', 'JobController@pendingServices');
Route::get('/old', 'JobController@old');
Route::get('/cancel-jobs', 'JobController@cancelJobs');
Route::get('/pay-jobs', 'JobController@payJobs');
Route::get('/pending-jobs', 'JobController@pendingJobs');
Route::get('/job/my-jobs', 'JobController@myJobs');
Route::get('/job/filters', 'JobController@filters');
Route::post('/job/delete', 'JobController@delete');
Route::get('/employee/profile', 'EmployeeController@index');
Route::get('/contact', 'ContactController@index')->name('contact.index');
Route::post('/contact/store', 'ContactController@store')->name('contact.store');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/politics', 'HomeController@politics')->name('politics');
Route::get('/payment/{type}/{id}/{source?}', 'PaymentController@index')->name('payment.index');
Route::post('/payment/process', 'PaymentController@process')->name('payment.process');
Route::post('/payment/new', 'PaymentController@newPayment')->name('payment.new');
Route::get('/postulation/{job}', 'PostulationController@store');
Route::get('/postulation', 'PostulationController@index')->name('postulations.index');
Route::post('/confirmation', 'PostulationController@confirmation');
Route::get('/notification/view', 'NotificationController@setViews');
Route::post('/qualification/store', 'QualificationController@store')->name('qualification.store');
Route::post('/payment/paypal', 'PaypalController@payWithpaypal')->name('paypal.complete');
Route::get('/payment/status', 'PaypalController@getPaymentStatus')->name('paypal.status');
Route::get('/test','TestController@test');
Route::get('/movil/payment/status/{status}','PaymentController@statusPaymentMovil');
Route::get('/getCategories','ServiceController@getCategories')->name('getCategories');


Route::get('/',function(){
    return  redirect()->route('job.index');
});

// Route::group(['prefix' => 'admin'], function () {
Route::namespace('Admin')->prefix('4dmil7')->name('admin.')->group(function () {

    Route::get('/dashboard', 'AdminController@index')->name('dashboard');
    Route::resource('/users','AdminUserController');
    Route::resource('/jobs','AdminJobController');
    Route::resource('/services','AdminServiceController');

});

app/Service.php
<?php

namespace TrabajoExpress;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use Searchable;

    public function toSearchableArray()
    {
        /**
         * Load the categories relation so that it's
         * available in the Laravel toArray() method
         */

        $array = $this->toArray();
        $array = $this->transform($array);

        $array['category'] = $this->category->name;

        return $array;
    }

    protected $fillable = [
        'photo', 
        'category_id',	
        'title',
        'description',
        'slug',
        'status',
        'address',
        'phone',
        'latitude',
        'longitude',
        'email',

    ];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
    public function category()
    {
        return $this->belongsTo(CategoryService::class);
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace TrabajoExpress\Http\Controllers;

use TrabajoExpress\Service;
use TrabajoExpress\CategoryService;
use TrabajoExpress\Http\Requests\ServiceRequest;

use Illuminate\Http\Request;
use Auth;
use Image;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $jobs = Service::paginate(15);
        $titleTab = 'Negocios';

        if($request->ajax()){
            return response()->json(
                view('job.jobs_catalog',compact('jobs','titleTab'))->render()
            );
        }
      
        $categories = CategoryService::all();

        return view('home', compact('jobs','categories','titleTab'));
    }

    public function MyServices(Request $request){
        $services = Service::where('user_id', Auth::user()->id)->paginate(6);

        if($request->ajax()){
            return response()->json(
                view('job.jobs_catalog',compact('jobs','titleTab'))->render()
            );
        }
      

        return view('service.index', compact('services'));
    }

    public function delete(Request $request)
    {
        $service = Service::find($request->service_id);
        $serviceName = $service->title;
        $file_path = public_path().'/img/services/'.$service->photo;
        \File::delete($file_path);
        $service->delete();

        return response('El Negocio '.$serviceName.' se ha eliminado');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = CategoryService::all();
      

        return view('service.create', compact('categories'));
    }

    public function getCategories(Request $request){

        $categories = CategoryService::all();
        return response($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServiceRequest $request)
    {
        if (isset($request->validator) && $request->validator->fails()) {
            return redirect()->back()->withErrors([$request->validator->errors()->all()]);
        }else{
            $newService = new Service($request->except('photo'));

            Auth::user()->services()->save($newService);
            $newSlug =  str_replace(" ", "-", "$request->title");
            $newService->slug =  $newSlug.'-'.$newService->id;
            $newService->views = 0;

            if($request->hasFile('photo')){
                $nameFile = '';
                $file = $request->file('photo');
                $nameFile = time().$file->getClientOriginalName();
                $thumbnail = Image::make($file)->resize(120, 120)->
                        save(public_path().'/img/services/thumbnails/'.$nameFile);
                $image = Image::make($file)->resize(1024, 720)->
                    save(public_path().'/img/services/'.$nameFile);
                $newService->photo = $nameFile;
            }
           
            $newService->status = 'Pendiente';
            $newService->save();

            return  redirect('/payment/service/'.$newService->id)->with('status', '¡Información Guardada Exitosamente!');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \TrabajoExpress\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        $service->views = $service->views + 1;
        $service->save(); 
        return view('service.show', compact('service'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \TrabajoExpress\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \TrabajoExpress\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \TrabajoExpress\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        //
    }
}

resources/views/service/create.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
@endsection

@section('content')
<!-- Header Title Start -->
<section class="inner-header-title"  style="background-image:url({{ asset('/img/banners/banner_service.jpg') }});">
    <div class="container">
        <h1>Ofrecer Negocio</h1>
    </div>
</section>
<div class="clearfix"></div>
<!-- Header Title End -->

<!-- General Detail Start -->
<div class="detail-desc section">
    <div class="container white-shadow">
    
        <form method="POST" class="add-feild" action="{{ route('service.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="detail-pic" id ="picUser">
                        {{-- src="{{ asset('/img/can-1.png') }} --}}
                    <img v-if="url" :src="url"  class="img" alt="" />
                    <a @click="trigger" href="javascript:void(0)" class="detail-edit" title="edit">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <input class ="d-none" type="file" name="photo" @change="onFileChange"  ref="fileInput">
                </div>
            </div>

            @include('commons.msg')
            @include('commons.errors')
            
            <div class="row bottom-mrg" id="formJob">
                <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">
                <div class="col-md-6 col-sm-6">
                    <div class="input-group">
                        <input  value="{{ old('title') }}" maxlength="32" required name="title" type="text" class="form-control" placeholder="Nombre de tu Empresa/Negocio">
                    </div>
                </div>
                
                {{-- <div class="col-md-6 col-sm-6">
                    <div class="input-group">
                        <select required id="selectCategory" name="category_id" class="form-control input-lg">
                            <option value="1">Categoría</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div> --}}
                <div class="col-md-6 col-sm-6">
                    <div class="input-group">
                        <input id="categories" class="form-control" required placeholder="Giro de tu negocio">
                        <input type="hidden" name="category_id" id="categorSelected" >
                        {{-- <input data-autocomplete="{{ route('getCategories') }}" /> --}}
                    </div>
                </div>
                {{-- <div class="col-md-6 col-sm-6 hide" id="openOther">
                    <label >Especifica otra categoría que no este en la lista</label>
                    <div class="input-group">
                        <input  name="other" type="text" class="form-control" placeholder="Específica otra" value="{{ old('other') }}" requiered >
                    </div>
                </div> --}}
                <div class="col-md-12 col-sm-12">
                    <label >Dirección del servicio</label>
                    <div class="input-group">
                        <input  required id="addressForm" readonly  name="address" value="{{ old('adress') }}" type="text" class="form-control openModal" placeholder="Dirección del Servicio.">
                        <input  value="{{ old('latitude') }}" id="latitude" type="hidden" name="latitude">
                        <input  value="{{ old('longitude') }}" id="longitude" type="hidden" name="longitude">
                    </div>
                </div>
                <div class="col-md-12 col-sm-12">
                    <label >Contacto del servicio</label>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="input-group">
                        <input  value="{{ old('phone') }}" oninput="maxLengthCheck(this, 10)"  name="phone" type="number" class="form-control" placeholder="Telefóno" required>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="input-group">
                        <input value="{{ old('email') }}" name="email" type="email" class="form-control" placeholder="Correo Electrónico" >
                    </div>
                </div>
                <div class="col-md-12 col-sm-12">
                    <textarea required name="description"  class="form-control" placeholder="Descripción">{{ old('description') }}"</textarea>
                </div>
            
                <div class="col-md-12 col-sm-12">
                    <button type="submit" class="btn btn-success btn-primary small-btn">Guardar</button>	
                </div>	
                    
            </div>
        </form>
    </div>
</div>




<!-- Modal -->
<div class="modal fade" id="myModalMap" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Ubicación</h5>
            <p>(Arrastra o Busca la dirección del trabajo)</p>
            <button type="button" class="close closeModal" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
                <div id="myMap"></div>
                <div class="col-md-12 col-sm-12 bt mb-1">
                    <label for="">Dirección:</label>
                    <div class="input-group">
                        <input  class="form-control" id="address" type="text" />
                        <span class="input-group-btn">
                            <button id="submit" type="button" class="btn btn-primary">Buscar</button>
                        </span>
                    </div>
                </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary closeModal">Guardar</button>
        </div>
        </div>
    </div>
    </div>
</div>
@include('modals.alert')

@endsection

@section('scripts')
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
       $.ajax({
                url: "{{ route('getCategories') }}",
                type: "GET",
                dataType: "json",
                success: function( resp ) {
                    var data =  $.map(resp,function(val) {
                        return {
                            value: val.name ,
                            id: val.id,
                        };
                    });
                    $("#categories").autocomplete({
                        source: data,
                        minLength: 0,
                        select: function( event, ui ) {
                           $('#categorSelected').val(ui.item.id);
                           console.log($('#categorSelected').val());
                        }
                    });
                }
            });

    </script>

    <script>
        function maxLengthCheck(object, size) {
        if (object.value.length >size)
            object.value = object.value.slice(0, size)
        }
        $('#selectCategory').change(function(){
            var optionSelected = $("option:selected", this);
            if(optionSelected.text() == 'Otra'){
                $('#openOther').addClass('show');
            }else{
                $('#openOther').removeClass('show');
            }
        });
    </script>

    <script>
        $('.openModal').click(function(){
            $('#myModalMap').addClass('d-block');

        });

        $('.closeModal').click(function(){
            $('#myModalMap').removeClass('d-block');

        });


        new Vue({
        el: '#picUser',
        data:{
            url: '/img/services/service.png',
        },
            methods: {
                trigger () {
                    this.$refs.fileInput.click()
                },
                onFileChange(e) {
                    const file = e.target.files[0];
                    this.url = URL.createObjectURL(file);
                }
            }
        });
    </script>

    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCklaCU8LI1jGPMNZweSImXr_wOn-0aMr4">
    </script>
    <script>
        $(document).ready(function() {
            var map, infoWindow;
            function initialize() {

            map = new google.maps.Map(document.getElementById('myMap'), {
            center: {lat: -34.397, lng: 150.644},
            zoom: 18,
            mapTypeId: google.maps.MapTypeId.ROADMAP
            });
            infoWindow = new google.maps.InfoWindow;
            var geocoder = new google.maps.Geocoder();

            var pos = {
                lat: 0,
                lng: 0
            };


            marker = new google.maps.Marker({
                map: map,
                position: pos,
                draggable: true,
            });

            // Try HTML5 geolocation.
            if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
            
                pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                marker.setPosition(pos);
                infoWindow.open(map);
                map.setCenter(pos);


                geocoder.geocode({ 'latLng': pos }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            $('#address').val(results[0].formatted_address);
                            $('#addressForm').val(results[0].formatted_address);
                            $('#latitude').val(marker.getPosition().lat());
                            $('#longitude').val(marker.getPosition().lng());
                            infoWindow.setContent(results[0].formatted_address);
                            infoWindow.open(map, marker);
                        }
                    }
                });



            }, function() {
                handleLocationError(true, infoWindow, map.getCenter());
            });
            } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infoWindow, map.getCenter());
            }

            document.getElementById('submit').addEventListener('click', function() {
                geocodeAddress(geocoder, map);
            });

            function geocodeAddress(geocoder, resultsMap) {
                var address = document.getElementById('address').value;
                geocoder.geocode({'address': address}, function(results, status) {
                    if (status === 'OK') {
                        $('#address').val(results[0].formatted_address);
                        $('#addressForm').val(results[0].formatted_address);
                        $('#latitude').val(marker.getPosition().lat());
                        $('#longitude').val(marker.getPosition().lng());
                        resultsMap.setCenter(results[0].geometry.location);
                        infoWindow.setContent(results[0].formatted_address);
                        marker.setPosition(results[0].geometry.location);
                        infoWindow.open(map, marker);

                    } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                    }
                });
            }

        

            google.maps.event.addListener(marker, 'dragend', function () {

                geocoder.geocode({ 'latLng': marker.getPosition() }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            $('#address').val(results[0].formatted_address);
                            $('#addressForm').val(results[0].formatted_address);
                            $('#latitude').val(marker.getPosition().lat());
                            $('#longitude').val(marker.getPosition().lng());
                            infoWindow.setContent(results[0].formatted_address);
                            infoWindow.open(map, marker);
                        }
                    }
                });
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);


        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                'Error: The Geolocation service failed.' :
                                'Error: Your browser doesn\'t support geolocation.');
            infoWindow.open(map);
        }
    });

    </script>
    
@endsection

resources/views/service/index.blade.php
@extends('layouts.app')


@section('content')
    <section class="inner-header-title" style="background-image:url({{ asset('/img/banners/banner_auth.jpg') }});">
        <div class="container">
            <h1>Mis Negocios</h1>
        </div>
    </section>

    <section class="manage-employee gray">
        <div class="container">
                <!-- search filter -->
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        @include('commons.msg')
                        <div class="search-filter">
                        
                            {{--  <div class="col-md-4 col-sm-5">
                                <div class="filter-form">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Buscar...">
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-default">Buscar</button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                                
                            <div class="col-md-8 col-sm-7">
                                <div class="short-by pull-right">
                                    ordenar por
                                    <div class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">por fecha <i class="fa fa-angle-down" aria-hidden="true"></i></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">por fecha</a></li>
                                        <li><a href="#">por vistas</a></li>
                                        <li><a href="#">por postulados</a></li>
                                    </ul>
                                    </div>
                                </div>
                            </div>  --}}
                            
                        </div>
                    </div>
                </div>
            <div class="">
                <div class="deatil-tab-employ tool-tab">
                      <ul class="nav simple nav-tabs" id="simple-design-tab">
                          <li class="active"><a href="#allPostuls">Todos</a></li>
                          <li><a href="#address">Pendientes</a></li>
                          <li><a href="#matches-job">Aceptados</a></li>
                          <li><a href="#friends">Cancelados</a></li>
                      </ul>
                      
                      <!-- Start All Sec -->
                      <div class="tab-content">
                          <!-- Start Friend List -->
                          <div id="allPostuls" class="tab-pane  active">
                              <div class="row">
                                  @foreach ($services as $service) 
                                      <div class="col-md-4 col-sm-4 serviceContent" id="{{$service->id}}">
                                          <div class="manage-cndt">
                                            <div class="pull-right">
                                                <div class="btn-group action-btn fix-btn-action">
                                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                        <i class="fa fa-ellipsis-v"></i>
                                                    </button>
                                                    <ul class="dropdown-menu pull-right" role="menu">
                                                        <li><a href="#"><i class="fa fa-edit"></i> Editar</a></li>
                                                        <li><a class="deleteBtn" href="javascript:;"><i class="fa fa-trash"></i> Eliminar</a></li>
                                                        <li><a href="service/{{$service->slug}}"><i class="fa fa-eye"></i> Ver</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <span style="left: -5px;" class="tg-themetag tg-featuretag {{ ($service->status == 'Cancelada'  ? 'tg-cancel' : ( $service->status == 'Pendiente'  ? 'tg-warning' : 'tg-success') ) }}">{{$service->status}}</span>
                                            <div class="cndt-caption">
                                                  <div class="cndt-pic">
                                                          @empty($service->photo)
                                                          @if ($service->category->name != 'Express')
                                                              <i class="cat-{{ $service->category->icon }} cat-photo-detail"></i>
                                                          @else
                                                              <i class="icon-express" style="    font-size: 3em;
                                                              position: relative;
                                                              top: 18px;
                                                              right: 0;
                                                              color: white;
                                                              cursor: pointer;" ></i>
                              
                                                          @endif
                                                      @else
                                                          <img src="{{ asset('/img/services/'.$service->photo) }}" class="img-responsive" alt="">
                                                      @endempty
                                                  </div>
                                                  <span>{{$service->user->state.', '.$service->user->city}}</span>
                                                  <h4>{{$service->title}}</h4>
                                                  <p>{{str_limit( $service->description, 32)}}</p>

                                              </div>
                                              <a  href="service/{{$service->slug}}" title="" class="cndt-profile-btn">Ver Negocio</a>
                                             
                                          </div>
                                      </div>
                                  @endforeach
                          </div>
                          
                      </div>
                      <!-- Start All Sec -->
                  </div>  
              </div>
          </div>
            <div class="paginate-center">
                {!! $services->render() !!}
            </div>
        </div>
    </section>

@endsection


@section('scripts')
    <script>
        $('.deleteBtn').click(function(){
            var service_id = $(this).closest('.serviceContent').attr('id');
            var service = $(this).closest('.serviceContent');


            var url = "/service/delete";
            var token = $('#csrf-token-id').attr('content');
            
            $.ajax({
                url: url,
                headers: {'X-CSRF-TOKEN': token},
                type: 'POST',
                data: { 'service_id': service_id},
                success: function(response){
                    service.remove();
                    alert(response);
                }
            });
        });
    </script>
@endsection